initialized code

diff --git a/.github/workflows/01-buidling-blocks.yaml b/.github/workflows/01-buidling-blocks.yaml
--- a/.github/workflows/01-buidling-blocks.yaml
+++ b/.github/workflows/01-buidling-blocks.yaml
@@ -11,6 +11,8 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - name: Failed step
-              run: echo "I will fail"
+              run: |
+                echo "I will fail"
+                exit 1
             - name: Say goodbye
               run: echo "Goodbye!"
